#
# Copyright (c) 2022, Rivos Inc. and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.  Oracle designates this
# particular file as subject to the "Classpath" exception as provided
# by Oracle in the LICENSE file that accompanied this code.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
#

name: 'OpenJDK Downstreaming'

on:
  schedule:
    # Trigger on Sunday to Friday at 21:00 UTC (23:00 CET, 14:00 PT)
    # It triggers at least 9 hours before start of the working day in CET
    # since that's when I would want to review it. And given GHA takes a long
    # time to run, we want to start doing it as early as possible
    - cron: '0 21 * * 0-4'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  fetch-push-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: "Fetch"
        id: fetch
        run: |
          git remote add upstream https://github.com/openjdk/jdk.git
          git fetch --tags upstream master

          TAG=$(git tag | grep --extended-regexp '^jdk\-.*' | sort --version-sort | tail --lines 1 | tr --delete '\n')
          test -n "$TAG"

          echo "::set-output name=tag::$TAG"

      - name: "Push"
        run: |
          git push origin ${{ steps.fetch.outputs.tag }}

          git checkout -B rivos/merge-upstream ${{ steps.fetch.outputs.tag }}
          git push origin rivos/merge-upstream

          git checkout -B master upstream/master
          git push origin master

      - name: "Create PR"
        run: |
          gh pr create \
            --repo rivosinc/jdk \
            --base rivos/main \
            --head rivos/merge-upstream \
            --title "Merge ${{ steps.fetch.outputs.tag }} into rivos/main" \
            --body "" \
            --reviewer "luhenry" || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
