#
# Copyright (c) 2022, Rivos Inc. and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.  Oracle designates this
# particular file as subject to the "Classpath" exception as provided
# by Oracle in the LICENSE file that accompanied this code.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
#

name: '[Rivos] Tag Release'

on:
  pull_request:
    types:
      - closed

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && github.event.pull_request.base.ref == "rivos/main" && github.event.pull_request.head.ref == "rivos/merge-upstream"
    steps:
      - uses: actions/checkout@v3
      - name: "Set Tag"
        id: set-tag
        run: |
          TAG="${{ github.event.pull_request.milestone.title }}-rivos"
          test -n "$TAG"
          echo "::set-output name=tag::$TAG"
      - name: "Push"
        run: |
          git tag --annotate ${{ steps.set-tag.outputs.tag }} HEAD
          git push origin ${{ steps.set-tag.outputs.tag }}
